const productsclothes = [
    {   id: 'jeans',
        code : 'j1',
        url: '/images/clothes/jeans/slim/Capture1.1.jpg', 
        detailUrl: '/images/clothes/jeans/slim/Capture1.3.jpg',
        title: {
            shortTitle: 'Slim',
            longTitle: 'Black Jeans'
        }, 
        price:250,
        description: 'Experience comfort and style with our new Slim Fit Jeans. Perfect for any occasion, these jeans are designed to offer a sleek and appealing silhouette. Made from high-quality denim, these jeans blend durability with a comfortable feel, ensuring all-day comfort.',
        discount: 0, 
        category: 'slim',
        color : 'black',
        material : 'Cotton',
        size: {XS:2,
               S:0,
               M:5,
               L:6,
               XL:2},
        gender: 'male'
     },
        { id: 'jeans',
        code : 'j2',
        url: '/images/clothes/jeans/slim/Capture2.1.jpg', 
        detailUrl: '/images/clothes/jeans/slim/Capture2.3.jpg',
        title: {
            shortTitle: 'Slim',
            longTitle: 'Blue Slim'
        }, 
        price:250,
        description: 'Experience comfort and style with our new Slim Fit Jeans. Perfect for any occasion, these jeans are designed to offer a sleek and appealing silhouette. Made from high-quality denim, these jeans blend durability with a comfortable feel, ensuring all-day comfort.',
        discount:1, 
        category: 'slim',
        color : 'blue',
        material : 'elastic',
        size: {XS:3,
               S:5,
               M:2,
               L:0,
               XL:4},
        gender: 'male'
	}
	,{ id: 'jeans',
        code : 'j3',
        url: '/images/clothes/jeans/slim/Capture3.1.jpg', 
        detailUrl: '/images/clothes/jeans/slim/Capture3.3.jpg',
        title: {
            shortTitle: 'Slim',
            longTitle: 'Blue Slim'
        }, 
        price:250,
        description: 'Experience comfort and style with our new Slim Fit Jeans. Perfect for any occasion, these jeans are designed to offer a sleek and appealing silhouette. Made from high-quality denim, these jeans blend durability with a comfortable feel, ensuring all-day comfort.',
        discount:10, 
        category: 'slim',
        color : 'blue',
        material : 'elastic',
        size: {XS:1,
               S:3,
               M:5,
               L:4,
               XL:4},
         gender: 'male'
        },
        { id: 'jeans',
        code: 'j4',
        url: '/images/clothes/jeans/slim/Capture4.1.jpg', 
        detailUrl: '/images/clothes/jeans/slim/Capture4.3.jpg',
        title: {
            shortTitle: 'Slim',
            longTitle: 'Light Blue Slim'
        }, 
        price: 250,
        description: 'Blugii tip trapez sunt piesa esențială de garderobă pentru cei care caută un stil retro, dar modern',
        discount: 20, 
        category: 'slim',
        color : 'blue',
        material : 'cotton',
        size: {XS:2,
               S:10,
               M:5,
               L:6,
               XL:2},
        gender: 'male'

        },

        { id: 'jeans',
        code: 'j5',
        url: '/images/clothes/jeans/skinny/CaptureSkinny1.1.jpg', 
        detailUrl: '/images/clothes/jeans/skinny/CaptureSkinny1.3.jpg',
        title: {
            shortTitle: 'Skinny',
            longTitle: 'Black Skinny'
        }, 
        price: 200,
        description: 'Elevate your style with our premium Skinny Jeans, the perfect blend of fashion-forward design and unparalleled comfort. These jeans are a staple for those who love a closer fit that highlights their silhouette, ideal for creating a variety of trendy looks.',
        discount: 1, 
        category: 'skinny',
        color : 'black',
        material : 'elastic',
        size: {XS:2,
               S:5,
               M:3,
               L:6,
               XL:2},
               gender: 'male'
        },
        {   id: 'jeans',
        code : 'j6',
        url: '/images/clothes/jeans/skinny/CaptureSkinny2.1.jpg', 
        detailUrl: '/images/clothes/jeans/skinny/CaptureSkinny2.3.jpg',
        title: {
            shortTitle: 'Skinny',
            longTitle: 'Blue'
        }, 
        price: 200,
        description: 'Elevate your style with our premium Skinny Jeans, the perfect blend of fashion-forward design and unparalleled comfort. These jeans are a staple for those who love a closer fit that highlights their silhouette, ideal for creating a variety of trendy looks.',
        discount: 15, 
        category: 'skinny',
        color : 'blue',
        material : 'elastic',
        size: {XS:2,
               S:1,
               M:3,
               L:6,
               XL:2},
               gender: 'male'
        },
	 {   id: 'jeans',
        code: 'j7',
        url: '/images/clothes/jeans/skinny/CaptureSkinny3.1.jpg', 
        detailUrl: '/images/clothes/jeans/skinny/CaptureSkinny3.3.jpg',
        title: {
            shortTitle: 'Skinny',
            longTitle: 'Grey Skinny'
        }, 
        price: 220,
        description: 'Elevate your style with our premium Skinny Jeans, the perfect blend of fashion-forward design and unparalleled comfort. These jeans are a staple for those who love a closer fit that highlights their silhouette, ideal for creating a variety of trendy looks.',
        discount: 10, 
        category: 'skinny',
        color : 'grey',
        material : 'elastic',
        size: {XS:2,
               S:0,
               M:3,
               L:6,
               XL:2},
               gender: 'male'
        },
	{   id: 'jeans',
        code: 'j8',
        url: '/images/clothes/jeans/skinny/CaptureSkinny5.1.jpg', 
        detailUrl: '/images/clothes/jeans/skinny/CaptureSkinny5.3.jpg',
        title: {
            shortTitle: 'Skinny',
            longTitle: 'Black Skinny'
        }, 
        price: 300,
        description: 'Elevate your style with our premium Skinny Jeans, the perfect blend of fashion-forward design and unparalleled comfort. These jeans are a staple for those who love a closer fit that highlights their silhouette, ideal for creating a variety of trendy looks.',
        discount: 35, 
        category: 'skinny',
        color : 'black',
        material : 'elastic',
        size: {XS:2,
               S:1,
               M:3,
               L:6,
               XL:2},
               gender: 'male'
        },
	 {   id: 'jeans',
        code: 'j9',
        url: '/images/clothes/jeans/loose/CaptureLoose1.1.jpg', 
        detailUrl: '/images/clothes/jeans/loose/CaptureLoose1.3.jpg',
        title: {
            shortTitle: 'Loose',
            longTitle: 'Black Loose'
        }, 
        price:300,
        description: 'Step into a world of ultimate comfort with our Relaxed Loose Fit Jeans. Designed for those who prioritize both comfort and style, these jeans are perfect for a laid-back yet stylish look. Their relaxed fit offers freedom of movement and a breezy feel, making them an ideal choice for everyday wear.',
        discount: 0, 
        category: 'loose',
        color : 'black',
        material : 'cotton',
        size: {XS:3,
               S:12,
               M:3,
               L:6,
               XL:2},
               gender: 'male'
        },
	 {   id: 'jeans',
        code: 'j10',
        url: '/images/clothes/jeans/loose/CaptureLoose2.1.jpg', 
        detailUrl: '/images/clothes/jeans/loose/CaptureLoose2.3.jpg',
        title: {
            shortTitle: 'Loose',
            longTitle: 'Blue Loose'
        }, 
        price:300,
        description: 'Step into a world of ultimate comfort with our Relaxed Loose Fit Jeans. Designed for those who prioritize both comfort and style, these jeans are perfect for a laid-back yet stylish look. Their relaxed fit offers freedom of movement and a breezy feel, making them an ideal choice for everyday wear.',
        discount: 5, 
        category: 'loose',
        color : 'blue',
        material : 'cotton',
        size: {XS:3,
               S:12,
               M:3,
               L:6,
               XL:2},
               gender: 'male'
        },
	 {   id: 'jeans',
        code: 'j11',
        url: '/images/clothes/jeans/loose/CaptureLoose3.1.jpg', 
        detailUrl: '/images/clothes/jeans/loose/CaptureLoose3.3.jpg',
        title: {
            shortTitle: 'Loose',
            longTitle: 'Blue Loose'
        }, 
        price:300,
        description: 'Step into a world of ultimate comfort with our Relaxed Loose Fit Jeans. Designed for those who prioritize both comfort and style, these jeans are perfect for a laid-back yet stylish look. Their relaxed fit offers freedom of movement and a breezy feel, making them an ideal choice for everyday wear.',
        discount: 0, 
        category: 'loose',
        color : 'black',
        material : 'cotton',
        size: {XS:3,
               S:12,
               M:3,
               L:6,
               XL:2},
               gender: 'male'
        },
	 {   id: 'jeans',
        code: 'j12',
        url: '/images/clothes/jeans/loose/CaptureLoose4.1.jpg', 
        detailUrl: '/images/clothes/jeans/loose/CaptureLoose4.3.jpg',
        title: {
            shortTitle: 'Loose',
            longTitle: 'Grey Loose'
        }, 
        price:300,
        description: 'Step into a world of ultimate comfort with our Relaxed Loose Fit Jeans. Designed for those who prioritize both comfort and style, these jeans are perfect for a laid-back yet stylish look. Their relaxed fit offers freedom of movement and a breezy feel, making them an ideal choice for everyday wear.',
        discount: 0, 
        category: 'loose',
        color : 'grey',
        material : 'cotton',
        size: {XS:3,
               S:12,
               M:3,
               L:6,
               XL:2},
               gender: 'male'
        },
	 {   id: 'jeans',
        code : 'j13',
        url: '/images/clothes/jeans/loose/CaptureLoose5.1.jpg', 
        detailUrl: '/images/clothes/jeans/loose/CaptureLoose5.3.jpg',
        title: {
            shortTitle: 'Loose',
            longTitle: 'Black Loose'
        }, 
        price:350,
        description: 'Step into a world of ultimate comfort with our Relaxed Loose Fit Jeans. Designed for those who prioritize both comfort and style, these jeans are perfect for a laid-back yet stylish look. Their relaxed fit offers freedom of movement and a breezy feel, making them an ideal choice for everyday wear.',
        discount: 0, 
        category: 'loose',
        color : 'black',
        material : 'cotton',
        size: {XS:3,
               S:12,
               M:3,
               L:6,
               XL:2},
               gender: 'male'
        }
	,
        {  id: 'hoodie',
        code: 'sw1',
        url: '/images/clothes/hoodie/imprimeu/CaptureHanoracImprimeu7.1.jpg', 
        detailUrl: '/images/clothes/hoodie/imprimeu/CaptureHanoracImprimeu7.3.jpg',
        title: {
            shortTitle: 'Hoodie',
            longTitle: 'Black Printed Hoodie'
        }, 
        price: 200,
        description: 'Embrace comfort and style with our collection of ultra-comfortable hoodies. Perfect for those who appreciate a relaxed and laid-back look, our hoodies combine softness, warmth, and versatility, making them an essential addition to any casual wardrobe.',
        discount: 0, 
        category: 'printed',
        color : 'negru',
        material : 'molton',
        size: {XS:2,
               S:10,
               M:5,
               L:6,
               XL:2},
               gender: 'male'
        },
        {   id: 'hoodie',
        code : 'sw2',
        url: '/images/clothes/hoodie/imprimeu/CaptureHanoracImprimeu8.1.jpg', 
        detailUrl: '/images/clothes/hoodie/imprimeu/CaptureHanoracImprimeu8.3.jpg',
        title: {
            shortTitle: 'Hoodie',
            longTitle: 'Blue Printed Hoodie'
        }, 
        price:200,
        description: 'Embrace comfort and style with our collection of ultra-comfortable hoodies. Perfect for those who appreciate a relaxed and laid-back look, our hoodies combine softness, warmth, and versatility, making them an essential addition to any casual wardrobe.',
        discount: 5, 
        category: 'printed',
        color : 'blue',
        material : 'molton',
        size: {XS:2,
               S:10,
               M:5,
               L:6,
               XL:2},
               gender: 'male'
        }, 
        { id: 'hoodie',
        code: 'sw3',
        url: '/images/clothes/hoodie/imprimeu/CaptureHanoracImprimeu9.1.jpg', 
        detailUrl: '/images/clothes/hoodie/imprimeu/CaptureHanoracImprimeu9.3.jpg',
        title: {
            shortTitle: 'Hoodie',
            longTitle: 'Blue Printed Hoodie'
        }, 
        price: 240,
        description: 'Embrace comfort and style with our collection of ultra-comfortable hoodies. Perfect for those who appreciate a relaxed and laid-back look, our hoodies combine softness, warmth, and versatility, making them an essential addition to any casual wardrobe.',
        discount: 10, 
        category: 'printed',
        color : 'blue',
        material : 'molton',
        size: {XS:2,
               S:10,
               M:5,
               L:6,
               XL:2},
               gender: 'male'
        },
	    {   id: 'hoodie',
        code: 'sw4',
        url: '/images/clothes/hoodie/imprimeu/CaptureHanoracImprimeu10.1.jpg', 
        detailUrl: '/images/clothes/hoodie/imprimeu/CaptureHanoracImprimeu10.3.jpg',
        title: {
            shortTitle: 'Hoodie',
            longTitle: 'White Printed Hoodie'
        }, 
        price:240,
        description: 'Embrace comfort and style with our collection of ultra-comfortable hoodies. Perfect for those who appreciate a relaxed and laid-back look, our hoodies combine softness, warmth, and versatility, making them an essential addition to any casual wardrobe.',
        discount: 0, 
        category: 'printed',
        color : 'white',
        material : 'molton',
        size: {XS:2,
               S:10,
               M:5,
               L:6,
               XL:2},
               gender: 'male'
        },
        {   id: 'hoodie',
        code: 'sw5',
        url: '/images/clothes/hoodie/normal/CaptureHanoracNegru1.1.jpg', 
        detailUrl: '/images/clothes/hoodie/normal/CaptureHanoracNegru1.3.jpg',
        title: {
            shortTitle: 'Hoodie',
            longTitle: 'Black Hoodie'
        }, 
        price:250,
        description: 'Embrace comfort and style with our collection of ultra-comfortable hoodies. Perfect for those who appreciate a relaxed and laid-back look, our hoodies combine softness, warmth, and versatility, making them an essential addition to any casual wardrobe.',
        discount: 0, 
        category: 'normal',
        color : 'black',
        material : 'molton',
        size: {XS:2,
               S:10,
               M:5,
               L:6,
               XL:2},
               gender: 'male'
        },
	{   id: 'hoodie',
        code: 'sw6',
        url: '/images/clothes/hoodie/normal/CaptureHanorac2.1.jpg', 
        detailUrl: '/images/clothes/hoodie/normal/CaptureHanorac2.2.jpg',
        title: {
            shortTitle: 'Hoodie',
            longTitle: 'Brown Hoodie'
        }, 
        price:250,
        description: 'Embrace comfort and style with our collection of ultra-comfortable hoodies. Perfect for those who appreciate a relaxed and laid-back look, our hoodies combine softness, warmth, and versatility, making them an essential addition to any casual wardrobe.',
        discount: 10, 
        category: 'normal',
        color : 'brown',
        material : 'molton',
        size: {XS:2,
               S:10,
               M:5,
               L:6,
               XL:2},
               gender: 'male'
        },
        {   id: 'hoodie',
        code: 'sw7',
        url: '/images/clothes/hoodie/normal/CaptureHanorac4.1.jpg', 
        detailUrl: '/images/clothes/hoodie/normal/CaptureHanorac4.3.jpg',
        title: {
            shortTitle: 'Hoodie',
            longTitle: 'White Hoodie'
        }, 
        price:260,
        description: 'Embrace comfort and style with our collection of ultra-comfortable hoodies. Perfect for those who appreciate a relaxed and laid-back look, our hoodies combine softness, warmth, and versatility, making them an essential addition to any casual wardrobe.',
        discount: 0, 
        category: 'normal',
        color : 'white',
        material : 'molton',
        size: {XS:2,
               S:10,
               M:5,
               L:6,
               XL:2},
               gender: 'male'
        },
        {   id: 'hoodie',
        code: 'sw8',
        url: '/images/clothes/hoodie/normal/CaptureHanorac3.1.jpg', 
        detailUrl: '/images/clothes/hoodie/normal/CaptureHanorac3.3.jpg',
        title: {
            shortTitle: 'Hoodie',
            longTitle: 'Brown Hoodie'
        }, 
        price:250,
        description: 'Embrace comfort and style with our collection of ultra-comfortable hoodies. Perfect for those who appreciate a relaxed and laid-back look, our hoodies combine softness, warmth, and versatility, making them an essential addition to any casual wardrobe.',
        discount: 0, 
        category: 'normal',
        color : 'brown',
        material : 'molton',
        size: {XS:2,
               S:10,
               M:5,
               L:6,
               XL:2},
               gender: 'male'
        },
        {   id: 'hoodie',
        code: 'sw9',
        url: '/images/clothes/hoodie/normal/CaptureHanorac6.1.jpg', 
        detailUrl: '/images/clothes/hoodie/normal/CaptureHanorac6.2.jpg',
        title: {
            shortTitle: 'Hoodie',
            longTitle: 'Blue Hoodie'
        }, 
        price:250,
        description: 'Embrace comfort and style with our collection of ultra-comfortable hoodies. Perfect for those who appreciate a relaxed and laid-back look, our hoodies combine softness, warmth, and versatility, making them an essential addition to any casual wardrobe.',
        discount: 0, 
        category: 'normal',
        color : 'blue',
        material : 'molton',
        size: {XS:2,
               S:10,
               M:5,
               L:6,
               XL:2},
               gender: 'male'
        },
	{   id: 't-shirts',
        code: 't1',
        url: '/images/clothes/tshirt/polo/CaptureTricouPolo1.1.jpg', 
        detailUrl: '/images/clothes/tshirt/polo/CaptureTricouPolo1.2.jpg',
        title: {
            shortTitle: 'T-Shirt',
            longTitle: 'Polo T-Shirt'
        }, 
        price:80,
        description: 'T-shirts are a fundamental piece in any wardrobe, offering the perfect blend of simplicity and style. They are easy to pair with jeans, shorts, skirts, or under a jacket or blazer. Suitable for a casual day out, a workout session, or an evening gathering, our t-shirts are versatile enough to adapt to your lifestyle and fashion needs.',
        discount: 0, 
        category: 'polo',
        color : 'white',
        material : 'cotton',
        size: {XS:2,
               S:10,
               M:5,
               L:6,
               XL:2},
               gender: 'male'
        },
	{   id: 't-shirts',
        code: 't2',
        url: '/images/clothes/tshirt/polo/CaptureTricouPolo2.1.jpg', 
        detailUrl: '/images/clothes/tshirt/polo/CaptureTricouPolo2.3.jpg',
        title: {
            shortTitle: 'T-Shirt',
            longTitle: 'Polo T-Shirt'
        }, 
        price:60,
        description: 'T-shirts are a fundamental piece in any wardrobe, offering the perfect blend of simplicity and style. They are easy to pair with jeans, shorts, skirts, or under a jacket or blazer. Suitable for a casual day out, a workout session, or an evening gathering, our t-shirts are versatile enough to adapt to your lifestyle and fashion needs.',
        discount: 0, 
        category: 'polo',
        color : 'black',
        material : 'cotton',
        size: {XS:2,
               S:10,
               M:5,
               L:6,
               XL:2},
               gender: 'male'
        },
	{   id: 't-shirts',
        code: 't3',
        url: '/images/clothes/tshirt/polo/CaptureTricouPolo3.1.jpg', 
        detailUrl: '/images/clothes/tshirt/polo/CaptureTricouPolo3.3.jpg',
        title: {
            shortTitle: 'T-Shirt',
            longTitle: 'Polo T-Shirt'
        }, 
        price:70,
        description: 'T-shirts are a fundamental piece in any wardrobe, offering the perfect blend of simplicity and style. They are easy to pair with jeans, shorts, skirts, or under a jacket or blazer. Suitable for a casual day out, a workout session, or an evening gathering, our t-shirts are versatile enough to adapt to your lifestyle and fashion needs.',
        discount: 10, 
        category: 'polo',
        color : 'blue',
        material : 'cotton',
        size: {XS:2,
               S:10,
               M:5,
               L:6,
               XL:2},
               gender: 'male'
        },
	{   id: 't-shirts',
        code: 't4',
        url: '/images/clothes/tshirt/polo/CaptureTricouPolo4.1.jpg', 
        detailUrl: '/images/clothes/tshirt/polo/CaptureTricouPolo4.3.jpg',
        title: {
            shortTitle: 'T-Shirt',
            longTitle: 'Polo T-Shirt'
        }, 
        price:60,
        description: 'T-shirts are a fundamental piece in any wardrobe, offering the perfect blend of simplicity and style. They are easy to pair with jeans, shorts, skirts, or under a jacket or blazer. Suitable for a casual day out, a workout session, or an evening gathering, our t-shirts are versatile enough to adapt to your lifestyle and fashion needs.',
        discount: 0, 
        category: 'polo',
        color : 'white',
        material : 'cotton',
        size: {XS:2,
               S:10,
               M:5,
               L:6,
               XL:2},
               gender: 'male'
        },
	{   id: 't-shirts',
        code: 't5',
        url: '/images/clothes/tshirt/basic/CaptureTricouBasic1.1.jpg', 
        detailUrl: '/images/clothes/tshirt/basic/CaptureTricouBasic1.3.jpg',
        title: {
            shortTitle: 'T-Shirt',
            longTitle: 'Basic T-Shirt'
        }, 
        price:50,
        description: 'T-shirts are a fundamental piece in any wardrobe, offering the perfect blend of simplicity and style. They are easy to pair with jeans, shorts, skirts, or under a jacket or blazer. Suitable for a casual day out, a workout session, or an evening gathering, our t-shirts are versatile enough to adapt to your lifestyle and fashion needs.',
        discount: 0, 
        category: 'basic',
        color : 'purpule',
        material : 'elastic',
        size: {XS:2,
               S:10,
               M:5,
               L:6,
               XL:2},
               gender: 'male'
        },
	{   id: 't-shirts',
        code: 't6',
        url: '/images/clothes/tshirt/basic/CaptureTricouBasic2.1.jpg', 
        detailUrl: '/images/clothes/tshirt/basic/CaptureTricouBasic2.3.jpg',
        title: {
            shortTitle: 'T-Shirt',
            longTitle: 'Basic T-Shirt'
        }, 
        price:50,
        description: 'T-shirts are a fundamental piece in any wardrobe, offering the perfect blend of simplicity and style. They are easy to pair with jeans, shorts, skirts, or under a jacket or blazer. Suitable for a casual day out, a workout session, or an evening gathering, our t-shirts are versatile enough to adapt to your lifestyle and fashion needs.',
        discount: 0, 
        category: 'basic',
        color : 'black',
        material : 'elastic',
        size: {XS:2,
               S:10,
               M:5,
               L:6,
               XL:2},
               gender: 'male'
        },
	{   id: 't-shirts',
        code: 't7',
        url: '/images/clothes/tshirt/basic/CaptureTricouBasic3.1.jpg', 
        detailUrl: '/images/clothes/tshirt/basic/CaptureTricouBasic3.3.jpg',
        title: {
            shortTitle: 'T-Shirt',
            longTitle: 'Basic T-Shirt'
        }, 
        price:50,
        description: 'T-shirts are a fundamental piece in any wardrobe, offering the perfect blend of simplicity and style. They are easy to pair with jeans, shorts, skirts, or under a jacket or blazer. Suitable for a casual day out, a workout session, or an evening gathering, our t-shirts are versatile enough to adapt to your lifestyle and fashion needs.',
        discount: 0, 
        category: 'basic',
        color : 'grey',
        material : 'elastic',
        size: {XS:2,
               S:10,
               M:5,
               L:6,
               XL:2},
               gender: 'male'
        },
	{   id: 't-shirts',
        code: 't8',
        url: '/images/clothes/tshirt/basic/CaptureTricouBasic4.1.jpg', 
        detailUrl: '/images/clothes/tshirt/basic/CaptureTricouBasic4.3.jpg',
        title: {
            shortTitle: 'T-Shirt',
            longTitle: 'Basic T-Shirt'
        }, 
        price:50,
        description: 'T-shirts are a fundamental piece in any wardrobe, offering the perfect blend of simplicity and style. They are easy to pair with jeans, shorts, skirts, or under a jacket or blazer. Suitable for a casual day out, a workout session, or an evening gathering, our t-shirts are versatile enough to adapt to your lifestyle and fashion needs.',
        discount: 0, 
        category: 'basic',
        color : 'white',
        material : 'elastic',
        size: {XS:2,
               S:10,
               M:5,
               L:6,
               XL:2},
               gender: 'male'
        },
        {   id: 'jeans',
        code : 'jw1',
        url: '/images/clothes/womenjeans/evazati/BlugiAlbiEvazati4.1.jpg', 
        detailUrl: '/images/clothes/womenjeans/evazati/BlugiAlbiEvazati4.2.jpg',
        title: {
            shortTitle: 'Evazat',
            longTitle: 'White Jeans'
        }, 
        price:250,
        description: 'Flared jeans, an iconic wardrobe staple, are making a strong comeback, bringing with them a touch of 70s nostalgia and a relaxed elegance. With a cut that gently widens from the knee downwards, these jeans offer a flattering silhouette and supreme comfort.',
        discount: 0, 
        category: 'evazat',
        color : 'white',
        material : 'Cotton',
        size: {XS:2,
               S:0,
               M:5,
               L:6,
               XL:2},
        gender: 'female'
     },
     {   id: 'jeans',
        code : 'jw2',
        url: '/images/clothes/womenjeans/evazati/BlugiGriEvazati3.1.jpg', 
        detailUrl: '/images/clothes/womenjeans/evazati/BlugiGriEvazati3.1.jpg',
        title: {
            shortTitle: 'Evazat',
            longTitle: 'Gray Jeans'
        }, 
        price:280,
        description: 'Flared jeans, an iconic wardrobe staple, are making a strong comeback, bringing with them a touch of 70s nostalgia and a relaxed elegance. With a cut that gently widens from the knee downwards, these jeans offer a flattering silhouette and supreme comfort.',
        discount: 5, 
        category: 'evazat',
        color : 'gray',
        material : 'Cotton',
        size: {XS:2,
               S:0,
               M:5,
               L:6,
               XL:2},
        gender: 'female'
     },
     {   id: 'jeans',
        code : 'jw3',
        url: '/images/clothes/womenjeans/evazati/BlugiNegriEvazati1.1.jpg', 
        detailUrl: '/images/clothes/womenjeans/evazati/BlugiNegriEvazati1.2.jpg',
        title: {
            shortTitle: 'Evazat',
            longTitle: 'Black Jeans'
        }, 
        price:245,
        description: 'Flared jeans, an iconic wardrobe staple, are making a strong comeback, bringing with them a touch of 70s nostalgia and a relaxed elegance. With a cut that gently widens from the knee downwards, these jeans offer a flattering silhouette and supreme comfort.',
        discount: 5, 
        category: 'evazat',
        color : 'black',
        material : 'elastic',
        size: {XS:2,
               S:3,
               M:0,
               L:6,
               XL:2},
        gender: 'female'
     },
     {   id: 'jeans',
        code : 'jw4',
        url: '/images/clothes/womenjeans/evazati/BlugiBlueEvazati2.1.jpg', 
        detailUrl: '/images/clothes/womenjeans/evazati/BlugiBlueEvazati2.2.jpg',
        title: {
            shortTitle: 'Evazat',
            longTitle: 'Blue Jeans'
        }, 
        price:275,
        description: 'Flared jeans, an iconic wardrobe staple, are making a strong comeback, bringing with them a touch of 70s nostalgia and a relaxed elegance. With a cut that gently widens from the knee downwards, these jeans offer a flattering silhouette and supreme comfort.',
        discount: 3, 
        category: 'evazat',
        color : 'blue',
        material : 'elastic',
        size: {XS:2,
               S:3,
               M:5,
               L:6,
               XL:2},
        gender: 'female'
     },
     {   id: 'jeans',
        code : 'jw5',
        url: '/images/clothes/womenjeans/mulati/BlugiMulati1.1.jpg', 
        detailUrl: '/images/clothes/womenjeans/mulati/BlugiMulati1.2.jpg',
        title: {
            shortTitle: 'Skinny',
            longTitle: 'Blue Jeans'
        }, 
        price:220,
        description: 'Skinny jeans remain a cornerstone of contemporary fashion, embodying sleek sophistication and versatile functionality. Meticulously designed to hug the contours of the body from waist to ankle, these jeans offer a streamlined silhouette that accentuates the figure. ',
        discount: 0, 
        category: 'skinny',
        color : 'blue',
        material : 'elastic',
        size: {XS:2,
               S:3,
               M:5,
               L:6,
               XL:2},
        gender: 'female'
     },
     {   id: 'jeans',
     code : 'jw6',
     url: '/images/clothes/womenjeans/mulati/BlugiMulati2.1.jpg', 
     detailUrl: '/images/clothes/womenjeans/mulati/BlugiMulati2.2.jpg',
     title: {
         shortTitle: 'Skinny',
         longTitle: 'Black Jeans'
     }, 
     price:250,
     description: 'Skinny jeans remain a cornerstone of contemporary fashion, embodying sleek sophistication and versatile functionality. Meticulously designed to hug the contours of the body from waist to ankle, these jeans offer a streamlined silhouette that accentuates the figure. ',
     discount:10, 
     category: 'skinny',
     color : 'black',
     material : 'elastic',
     size: {XS:2,
            S:3,
            M:5,
            L:6,
            XL:2},
     gender: 'female'
  },
  {   id: 'jeans',
     code : 'jw7',
     url: '/images/clothes/womenjeans/mulati/BlugiMulati3.1.jpg', 
     detailUrl: '/images/clothes/womenjeans/mulati/BlugiMulati3.2.jpg',
     title: {
         shortTitle: 'Skinny',
         longTitle: 'Blue Jeans'
     }, 
     price:250,
     description: 'Skinny jeans remain a cornerstone of contemporary fashion, embodying sleek sophistication and versatile functionality. Meticulously designed to hug the contours of the body from waist to ankle, these jeans offer a streamlined silhouette that accentuates the figure. ',
     discount:10, 
     category: 'skinny',
     color : 'blue',
     material : 'elastic',
     size: {XS:2,
            S:0,
            M:5,
            L:6,
            XL:2},
     gender: 'female'
  },
  {   id: 'jeans',
     code : 'jw8',
     url: '/images/clothes/womenjeans/slim/BlugiAlbastriSlim2.1.jpg', 
     detailUrl: '/images/clothes/womenjeans/slim/BlugiAlbastriSlim2.2.jpg',
     title: {
         shortTitle: 'Slim',
         longTitle: 'Blue Slim'
     }, 
     price:300,
     description: 'Slim-fit jeans strike the perfect balance between comfort and contour, offering a tailored look that is neither too tight nor too loose. This style is characterized by a closer fit through the hips and thighs, tapering slightly towards the ankles, which creates a sleek and polished silhouette. ',
     discount:30, 
     category: 'slim',
     color : 'blue',
     material : 'cotton',
     size: {XS:2,
            S:5,
            M:5,
            L:6,
            XL:2},
     gender: 'female'
  },
  {   id: 'jeans',
     code : 'jw9',
     url: '/images/clothes/womenjeans/slim/BlugiAlbi4.1.jpg', 
     detailUrl: '/images/clothes/womenjeans/slim/BlugiAlbi4.2.jpg',
     title: {
         shortTitle: 'Slim',
         longTitle: 'White Slim'
     }, 
     price:290,
     description: 'Slim-fit jeans strike the perfect balance between comfort and contour, offering a tailored look that is neither too tight nor too loose. This style is characterized by a closer fit through the hips and thighs, tapering slightly towards the ankles, which creates a sleek and polished silhouette. ',
     discount:10, 
     category: 'slim',
     color : 'white',
     material : 'cotton',
     size: {XS:2,
            S:5,
            M:5,
            L:6,
            XL:2},
     gender: 'female'
  },
  {   id: 'jeans',
  code : 'jw10',
  url: '/images/clothes/womenjeans/slim/BlugiNegriSlim1.1.jpg', 
  detailUrl: '/images/clothes/womenjeans/slim/BlugiNegriSlim2.1.jpg',
  title: {
      shortTitle: 'Slim',
      longTitle: 'Black Slim'
  }, 
  price:300,
  description: 'Slim-fit jeans strike the perfect balance between comfort and contour, offering a tailored look that is neither too tight nor too loose. This style is characterized by a closer fit through the hips and thighs, tapering slightly towards the ankles, which creates a sleek and polished silhouette. ',
  discount:5, 
  category: 'slim',
  color : 'black',
  material : 'cotton',
  size: {XS:5,
         S:2,
         M:5,
         L:6,
         XL:2},
  gender: 'female'
},
{   id: 'hoodie',
code : 'sww1',
url: '/images/clothes/womenhoodie/normal/CaptureBlackHoodie2.1.jpg', 
detailUrl: '/images/clothes/womenhoodie/normal/CaptureBlackHoodie2.2.jpg',
title: {
    shortTitle: 'Hoodie',
    longTitle: 'Black Hoodie'
}, 
price:300,
description: 'Embrace comfort and style with our collection of ultra-comfortable hoodies. Perfect for those who appreciate a relaxed and laid-back look, our hoodies combine softness, warmth, and versatility, making them an essential addition to any casual wardrobe. ',
discount:15, 
category: 'normal',
color : 'black',
material : 'molton',
size: {XS:5,
       S:0,
       M:5,
       L:6,
       XL:2},
gender: 'female'
},
{   id: 'hoodie',
code : 'sww2',
url: '/images/clothes/womenhoodie/normal/CaptureBlueHoodie1.1.jpg', 
detailUrl: '/images/clothes/womenhoodie/normal/CaptureBlueHoodie1.2.jpg',
title: {
    shortTitle: 'Hoodie',
    longTitle: 'Blue Hoodie'
}, 
price:300,
description: 'Embrace comfort and style with our collection of ultra-comfortable hoodies. Perfect for those who appreciate a relaxed and laid-back look, our hoodies combine softness, warmth, and versatility, making them an essential addition to any casual wardrobe. ',
discount:35, 
category: 'normal',
color : 'blue',
material : 'molton',
size: {XS:5,
       S:1,
       M:5,
       L:6,
       XL:2},
gender: 'female'
},
{   id: 'hoodie',
code : 'sww3',
url: '/images/clothes/womenhoodie/normal/CaptureCremHoodie11.1.jpg', 
detailUrl: '/images/clothes/womenhoodie/normal/CaptureCremHoodie12.1.jpg',
title: {
    shortTitle: 'Hoodie',
    longTitle: 'Cream Hoodie'
}, 
price:240,
description: 'Embrace comfort and style with our collection of ultra-comfortable hoodies. Perfect for those who appreciate a relaxed and laid-back look, our hoodies combine softness, warmth, and versatility, making them an essential addition to any casual wardrobe. ',
discount:5, 
category: 'normal',
color : 'cream',
material : 'molton',
size: {XS:5,
       S:1,
       M:5,
       L:6,
       XL:2},
gender: 'female'
},
{   id: 'hoodie',
code : 'sww4',
url: '/images/clothes/womenhoodie/normal/CaptureGrayHoodie6.1.jpg', 
detailUrl: '/images/clothes/womenhoodie/normal/CaptureGrayHoodie6.2.jpg',
title: {
    shortTitle: 'Hoodie',
    longTitle: 'Gray Hoodie'
}, 
price:290,
description: 'Embrace comfort and style with our collection of ultra-comfortable hoodies. Perfect for those who appreciate a relaxed and laid-back look, our hoodies combine softness, warmth, and versatility, making them an essential addition to any casual wardrobe. ',
discount:0, 
category: 'normal',
color : 'gray',
material : 'molton',
size: {XS:5,
       S:12,
       M:5,
       L:6,
       XL:2},
gender: 'female'
},
{   id: 'hoodie',
code : 'sww5',
url: '/images/clothes/womenhoodie/normal/CaptureWhiteHoodie7.1.jpg', 
detailUrl: '/images/clothes/womenhoodie/normal/CaptureWhiteHoodie7.2.jpg',
title: {
    shortTitle: 'Hoodie',
    longTitle: 'White Hoodie'
}, 
price:290,
description: 'Embrace comfort and style with our collection of ultra-comfortable hoodies. Perfect for those who appreciate a relaxed and laid-back look, our hoodies combine softness, warmth, and versatility, making them an essential addition to any casual wardrobe. ',
discount:0, 
category: 'normal',
color : 'white',
material : 'molton',
size: {XS:5,
       S:4,
       M:5,
       L:6,
       XL:2},
gender: 'female'
},
{   id: 'hoodie',
code : 'sww6',
url: '/images/clothes/womenhoodie/blouse/CaptureCremHoodie8.1.jpg', 
detailUrl: '/images/clothes/womenhoodie/blouse/CaptureCremHoodie8.2.jpg',
title: {
    shortTitle: 'Blouse',
    longTitle: 'Cream Hoodie'
}, 
price:290,
description: 'Embrace comfort and style with our collection of ultra-comfortable hoodies. Perfect for those who appreciate a relaxed and laid-back look, our hoodies combine softness, warmth, and versatility, making them an essential addition to any casual wardrobe. ',
discount:10, 
category: 'normal',
color : 'cream',
material : 'molton',
size: {XS:5,
       S:4,
       M:5,
       L:6,
       XL:2},
gender: 'female'
},
{   id: 'hoodie',
code : 'sww7',
url: '/images/clothes/womenhoodie/blouse/CaptureGreenHoodie9.1.jpg', 
detailUrl: '/images/clothes/womenhoodie/blouse/CaptureGreenHoodie9.2.jpg',
title: {
    shortTitle: 'Blouse',
    longTitle: 'Green Hoodie'
}, 
price:250,
description: 'Embrace comfort and style with our collection of ultra-comfortable blouse. Perfect for those who appreciate a relaxed and laid-back look, our hoodies combine softness, warmth, and versatility, making them an essential addition to any casual wardrobe. ',
discount:0, 
category: 'blouse',
color : 'green',
material : 'molton',
size: {XS:5,
       S:4,
       M:5,
       L:6,
       XL:2},
gender: 'female'
},
{   id: 'hoodie',
code : 'sww7',
url: '/images/clothes/womenhoodie/blouse/CaptureWhiteHoodie4.1.jpg', 
detailUrl: '/images/clothes/womenhoodie/blouse/CaptureWhiteHoodie4.2.jpg',
title: {
    shortTitle: 'Blouse',
    longTitle: 'White Hoodie'
}, 
price:250,
description: 'Embrace comfort and style with our collection of ultra-comfortable blouse. Perfect for those who appreciate a relaxed and laid-back look, our hoodies combine softness, warmth, and versatility, making them an essential addition to any casual wardrobe. ',
discount:0, 
category: 'blouse',
color : 'white',
material : 'Cotton',
size: {XS:5,
       S:1,
       M:5,
       L:6,
       XL:2},
gender: 'female'
},
{   id: 't-shirts',
code : 'tsw1',
url: '/images/clothes/womentshirts/basic/CaptureBlackCotton1.1.jpg', 
detailUrl: '/images/clothes/womentshirts/basic/CaptureBlackCotton2.1.jpg',
title: {
    shortTitle: 'T-Shirts',
    longTitle: 'Basic T-Shirt'
}, 
price:50,
description: 'T-shirts are a fundamental piece in any wardrobe, offering the perfect blend of simplicity and style. They are easy to pair with jeans, shorts, skirts, or under a jacket or blazer. Suitable for a casual day out, a workout session, or an evening gathering, our t-shirts are versatile enough to adapt to your lifestyle and fashion needs.',
discount:0, 
category: 'basic',
color : 'black',
material : 'Cotton',
size: {XS:5,
       S:1,
       M:5,
       L:6,
       XL:2},
gender: 'female'
},
{   id: 't-shirts',
code : 'tsw2',
url: '/images/clothes/womentshirts/basic/CaptureCremeCotton4.1.jpg', 
detailUrl: '/images/clothes/womentshirts/basic/CaptureCremeCotton4.2.jpg',
title: {
    shortTitle: 'T-Shirts',
    longTitle: 'Basic T-Shirt'
}, 
price:50,
description: 'T-shirts are a fundamental piece in any wardrobe, offering the perfect blend of simplicity and style. They are easy to pair with jeans, shorts, skirts, or under a jacket or blazer. Suitable for a casual day out, a workout session, or an evening gathering, our t-shirts are versatile enough to adapt to your lifestyle and fashion needs.',
discount:0, 
category: 'basic',
color : 'cream',
material : 'Cotton',
size: {XS:5,
       S:1,
       M:5,
       L:6,
       XL:2},
gender: 'female'
},
{   id: 't-shirts',
code : 'tsw3',
url: '/images/clothes/womentshirts/basic/CaptureGrayCotton3.1.jpg', 
detailUrl: '/images/clothes/womentshirts/basic/CaptureGrayCotton3.2.jpg',
title: {
    shortTitle: 'T-Shirts',
    longTitle: 'Basic T-Shirt'
}, 
price:65,
description: 'T-shirts are a fundamental piece in any wardrobe, offering the perfect blend of simplicity and style. They are easy to pair with jeans, shorts, skirts, or under a jacket or blazer. Suitable for a casual day out, a workout session, or an evening gathering, our t-shirts are versatile enough to adapt to your lifestyle and fashion needs.',
discount:5, 
category: 'basic',
color : 'gray',
material : 'Cotton',
size: {XS:5,
       S:1,
       M:5,
       L:6,
       XL:2},
gender: 'female'
},
{   id: 't-shirts',
code : 'tsw4',
url: '/images/clothes/womentshirts/basic/CaptureWhiteCotton2.1.jpg', 
detailUrl: '/images/clothes/womentshirts/basic/CaptureWhiteCotton2.2.jpg',
title: {
    shortTitle: 'T-Shirts',
    longTitle: 'Basic T-Shirt'
}, 
price:70,
description: 'T-shirts are a fundamental piece in any wardrobe, offering the perfect blend of simplicity and style. They are easy to pair with jeans, shorts, skirts, or under a jacket or blazer. Suitable for a casual day out, a workout session, or an evening gathering, our t-shirts are versatile enough to adapt to your lifestyle and fashion needs.',
discount:0, 
category: 'basic',
color : 'white',
material : 'Cotton',
size: {XS:5,
       S:1,
       M:5,
       L:6,
       XL:2},
gender: 'female'
},
{   id: 't-shirts',
code : 'tsw5',
url: '/images/clothes/womentshirts/basic/CaptureWhiteCotton6.1.jpg', 
detailUrl: '/images/clothes/womentshirts/basic/CaptureWhiteCotton6.2.jpg',
title: {
    shortTitle: 'T-Shirts',
    longTitle: 'Basic T-Shirt'
}, 
price:70,
description: 'T-shirts are a fundamental piece in any wardrobe, offering the perfect blend of simplicity and style. They are easy to pair with jeans, shorts, skirts, or under a jacket or blazer. Suitable for a casual day out, a workout session, or an evening gathering, our t-shirts are versatile enough to adapt to your lifestyle and fashion needs.',
discount:10, 
category: 'basic',
color : 'blue',
material : 'Cotton',
size: {XS:5,
       S:0,
       M:5,
       L:6,
       XL:2},
gender: 'female'
},
{   id: 't-shirts',
code : 'tsw6',
url: '/images/clothes/womentshirts/maieu/CaptureMaieuBlack1.1.jpg', 
detailUrl: '/images/clothes/womentshirts/maieu/CaptureMaieuBlack1.1.jpg',
title: {
    shortTitle: 'T-Shirts',
    longTitle: 'Normal T-Shirt'
}, 
price:50,
description: 'T-shirts are a fundamental piece in any wardrobe, offering the perfect blend of simplicity and style. They are easy to pair with jeans, shorts, skirts, or under a jacket or blazer. Suitable for a casual day out, a workout session, or an evening gathering, our t-shirts are versatile enough to adapt to your lifestyle and fashion needs.',
discount:0, 
category: 'normal',
color : 'black',
material : 'Cotton',
size: {XS:5,
       S:0,
       M:5,
       L:6,
       XL:2},
gender: 'female'
},
{   id: 't-shirts',
code : 'tsw7',
url: '/images/clothes/womentshirts/maieu/CaptureMaieuPurple3.1.jpg', 
detailUrl: '/images/clothes/womentshirts/maieu/CaptureMaieuPurple3.2.jpg',
title: {
    shortTitle: 'T-Shirts',
    longTitle: 'Normal T-Shirt'
}, 
price:50,
description: 'T-shirts are a fundamental piece in any wardrobe, offering the perfect blend of simplicity and style. They are easy to pair with jeans, shorts, skirts, or under a jacket or blazer. Suitable for a casual day out, a workout session, or an evening gathering, our t-shirts are versatile enough to adapt to your lifestyle and fashion needs.',
discount:2, 
category: 'normal',
color : 'violet',
material : 'Cotton',
size: {XS:5,
       S:0,
       M:5,
       L:6,
       XL:2},
gender: 'female'
},
{   id: 't-shirts',
code : 'tsw7',
url: '/images/clothes/womentshirts/maieu/CaptureMaieuWhite2.1.jpg', 
detailUrl: '/images/clothes/womentshirts/maieu/CaptureMaieuWhite2.2.jpg',
title: {
    shortTitle: 'T-Shirts',
    longTitle: 'Normal T-Shirt'
}, 
price:50,
description: 'T-shirts are a fundamental piece in any wardrobe, offering the perfect blend of simplicity and style. They are easy to pair with jeans, shorts, skirts, or under a jacket or blazer. Suitable for a casual day out, a workout session, or an evening gathering, our t-shirts are versatile enough to adapt to your lifestyle and fashion needs.',
discount:2, 
category: 'normal',
color : 'white',
material : 'Cotton',
size: {XS:5,
       S:0,
       M:5,
       L:6,
       XL:2},
gender: 'female'
},
{   id: 't-shirts',
code : 'tsw8',
url: '/images/clothes/womentshirts/oversize/CaptureBlackOversize2.1.jpg', 
detailUrl: '/images/clothes/womentshirts/oversize/CaptureBlackOversize2.2.jpg',
title: {
    shortTitle: 'T-Shirts',
    longTitle: 'Oversize T-Shirt'
}, 
price:50,
description: 'T-shirts are a fundamental piece in any wardrobe, offering the perfect blend of simplicity and style. They are easy to pair with jeans, shorts, skirts, or under a jacket or blazer. Suitable for a casual day out, a workout session, or an evening gathering, our t-shirts are versatile enough to adapt to your lifestyle and fashion needs.',
discount:2, 
category: 'oversize',
color : 'black',
material : 'Cotton',
size: {XS:5,
       S:0,
       M:5,
       L:6,
       XL:2},
gender: 'female'
},
{   id: 't-shirts',
code : 'tsw9',
url: '/images/clothes/womentshirts/oversize/CaptureBlueOversize3.1.jpg', 
detailUrl: '/images/clothes/womentshirts/oversize/CaptureBlueOversize3.2.jpg',
title: {
    shortTitle: 'T-Shirts',
    longTitle: 'Oversize T-Shirt'
}, 
price:100,
description: 'T-shirts are a fundamental piece in any wardrobe, offering the perfect blend of simplicity and style. They are easy to pair with jeans, shorts, skirts, or under a jacket or blazer. Suitable for a casual day out, a workout session, or an evening gathering, our t-shirts are versatile enough to adapt to your lifestyle and fashion needs.',
discount:5, 
category: 'oversize',
color : 'blue',
material : 'Cotton',
size: {XS:5,
       S:0,
       M:5,
       L:6,
       XL:2},
gender: 'female'
},
{   id: 't-shirts',
code : 'tsw10',
url: '/images/clothes/womentshirts/oversize/CaptureCremeOversize5.1.jpg', 
detailUrl: '/images/clothes/womentshirts/oversize/CaptureCremeOversize5.1.jpg',
title: {
    shortTitle: 'T-Shirts',
    longTitle: 'Oversize T-Shirt'
}, 
price:100,
description: 'T-shirts are a fundamental piece in any wardrobe, offering the perfect blend of simplicity and style. They are easy to pair with jeans, shorts, skirts, or under a jacket or blazer. Suitable for a casual day out, a workout session, or an evening gathering, our t-shirts are versatile enough to adapt to your lifestyle and fashion needs.',
discount:0, 
category: 'oversize',
color : 'blue',
material : 'Cotton',
size: {XS:5,
       S:5,
       M:5,
       L:6,
       XL:2},
gender: 'female'
},


     
    
]
module.exports=productsclothes;